spring.application.name=recouvrement-backend

# Connexion a Oracle 19c
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=ton_user_oracle
spring.datasource.password=Admise2026*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Port du serveur backend (Angular tourne deja sur 4200)
server.port=8080

# JWT (auth) - secret de dev uniquement, a deplacer en variable d'environnement avant toute mise en prod
jwt.secret=Nn3v2r5h4reTh1sSecretInProdPl3aseUseAnEnvVarInsteadOfAHardcodedValueOk?
# 24h en millisecondes
jwt.expiration-ms=86400000